/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/NaiveForm/src/BaseForm.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/basicModal.vue')['default']
    BasicUpload: typeof import('./src/components/Upload/src/BasicUpload.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/src/components/settings/ColumnSetting.vue')['default']
    EditableCell: typeof import('./src/components/Table/src/components/editable/EditableCell.vue')['default']
    Lockscreen: typeof import('./src/components/Lockscreen/Lockscreen.vue')['default']
    Message: typeof import('./src/components/NProvider/components/message.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    ND: typeof import('naive-ui')['ND']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDia: typeof import('naive-ui')['NDia']
    NDialog: typeof import('naive-ui')['NDialog']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProvider: typeof import('./src/components/NProvider/index.vue')['default']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NUse: typeof import('naive-ui')['NUse']
    Recharge: typeof import('./src/components/Lockscreen/Recharge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/ReText/src/index.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TableAction: typeof import('./src/components/Table/src/components/TableAction.vue')['default']
  }
}
