/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Service - version 1
 *
 * Service API
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'UserService.addUser': ['POST', '/user/add'],
  'UserService.login': ['POST', '/user/login'],
  'UserService.updateUser': ['POST', '/user/update']
};
